### ISSUE TITLE
Be mindful of runtime-private data structures

### ISSUE THREAD

**Issue by jckarter** [Azoy/Echo#6]
This library exposes a number of runtime-private data structures that may change in a future version of the Swift runtime, particularly the layou of runtime instantiated metadata structures such as Existential/Tuple/Metatype/FunctionTypeMetadata and the object layout of KeyPath instances. In fact, if you try to build this library with an asserts-enabled compiler, it will trip an assertion failure for using unsupported builtins on the resilient AnyKeyPath class. If you want to experiment with those, that's great, but you might want to factor parts of the codebase that use these runtime private structures into a separate package that is clearly marked experimental, so that people using this library do not inadvertently ship apps that will break on future Swift runtimes.

**Comment by Azoy** [comment]
> layou of runtime instantiated metadata structures such as Existential/Tuple/Metatype/FunctionTypeMetadata and the object layout of KeyPath instances.

Could you elaborate on how those metadata structures could change in the future? Is it simply the fact that they aren't emitted by the compiler that their layout can be changed freely?

I just read the ABI concerns portion of the KeyPath doc about how only the pattern is ABI, and the object layout can be changed freely which makes sense to me.

> In fact, if you try to build this library with an asserts-enabled compiler, it will trip an assertion failure for using unsupported builtins on the resilient AnyKeyPath class.

This was implemented to make a mock up implementation for the `Reflection.allKeyPaths` APIs that @dan-zheng @rxwei and I plan to move to either the standard library or a separate module that'll ship with Swift. I was unaware that this actually hit an assertion until recently pointed out on the forums. Ideally once that's (hopefully) approved and implemented, then my builtin hackey can go away.

---

Thanks Joe for taking a look at this and providing concerns. Going forward, what do I need to look for when adding structures here? Do I need to ensure that the compiler emits them in a binary to be considered ABI? Is this only a concern for apps being shipped on ABI stable platforms? If someone on a Linux based platform uses this, and a newer Swift version breaks their app, they simply have to update to the newer package right? It only becomes an issue once those platforms lock down ABI? Are there any other concerns you have that I can hopefully ensure that they're dealt with?

**Comment by jckarter** [comment]
> Could you elaborate on how those metadata structures could change in the future? Is it simply the fact that they aren't emitted by the compiler that their layout can be changed freely?

Since they aren't generated by the compiler, and the compiler doesn't generate code that relies on their layout (with the exception of `TupleTypeMetadata`, where the compiler knows the layout of the element types and offsets array so that it can more efficiently dereference generic tuple elements), there's no ABI constraint on their layout. If we add language features in the future, we may want to change the layouts of some of these structures. For instance, existential types would be nice to represent in a more generalized way by describing the `GenericContext` of the dynamic type, instead of having separate special case `Existential` and `ExistentialMetatype` records for the two kinds of existentials we support today.

Similarly, for key paths, we will probably introduce new kinds of components or new subclasses in the future, or we might implement optimizations that require changing the object layout.

> Thanks Joe for taking a look at this and providing concerns. Going forward, what do I need to look for when adding structures here? Do I need to ensure that the compiler emits them in a binary to be considered ABI? Is this only a concern for apps being shipped on ABI stable platforms? If someone on a Linux based platform uses this, and a newer Swift version breaks their app, they simply have to update to the newer package right? It only becomes an issue once those platforms lock down ABI? Are there any other concerns you have that I can hopefully ensure that they're dealt with?

Yes, on non-Apple platforms, there is no ABI stability, so someone upgrading their compiler would have to rebuild all their binaries regardless. The concern with ABI would be someone distributing an app or binary-only framework for an Apple OS that they expect to keep working when users upgrade their OS.

**Comment by vmanot** [comment]
@Azoy @jckarter  does this mean that `KeyPathIterable` is fragile?

**Comment by Azoy** [comment]
Yes. I’m working on moving this to the Swift project with some folks so that one doesn’t need to worry about breakage.

**Comment by vmanot** [comment]
@Azoy that's great to hear, please let me know if I can pitch in. I've got a [runtime library](https://github.com/vmanot/Runtime) that I'm actively working on, so I have a little bit of experience in that area.

**Comment by Azoy** [comment]
I've discussed this with some folks and I've come to the conclusion that I will keep some of these metadata structures within the `Echo` target, but I will be removing some of the experimental stuff like `EchoMirror` and `EchoProperties` (reflection keypaths is in the works in the evolution staging). Some of the solutions for things like TupleMetadata/FunctionMetadata/etc. included moving into a separate target, like Joe mentioned in the OP, namespacing them with `Unstable`, or even removing them entirely. I'll break down some of the reasons why I and others didn't agree on these alternatives.

1. Separate target:
This one might be the least bad option out of the three, however it comes at an API cost. The top level `reflect()` method would have to return a `Metadata?` because if it did come across one of the non ABI stable metadatas which is located in this separate target, it couldn't return said metadata. This isn't terrible, however it affects a lot of other APIs within Echo that I don't personally want for the library. There's also an issue with duplicated code that needs to be ported over from Echo to something like EchoUnstable, but that's not a major issue.

2. `Unstable` namespace:
While initially appealing at first, it ultimately doesn't make sense. For platforms who haven't declared ABI stability, all metadata are considered "unstable" and only having a select few be namespaced with this doesn't make sense. I could platformitize this so that only on platforms with ABI stability have this namespace, but then there's the issue of a separate API on different platforms which isn't great for user experience.

3. Removing them entirely:
Like using a separate target, this affects a lot of the other APIs within Echo that I don't personally want for the library. It's also worse than a separate target because then you don't have that functionality whatsoever, vs. importing an unstable target.

Instead, others have convinced me that libraries like this one should have large warning signs letting the user know that what they could be doing could break in a future Swift version. If one is deploying a Swift application on a platform that hasn't declared ABI stability, nothing should be guaranteed to work, however if they are deploying one on a platform that has, there will be select functionality that is stable and guaranteed to work across Swift versions. I will be updating documentation to indicate what is considered ABI stable and what is not across Echo along with updating the README informing users that this library does expose ABI unstable routines. Quoting one of the developers that I spoke with:

> If you're going to expose unstable stuff -- the entire lib is assumed unstable -- i.e. I could not use it if I "really really have to be stable"

Ideally in the future, Swift will adopt more and powerful reflection capabilities that make more use of its runtime metadata, ultimately making libraries like this one obsolete over time.
