### ISSUE TITLE
KeyPath support

### ISSUE THREAD

**Issue by lightsprint09** [Azoy/Echo#8]
Hi looks like this library has great potential building dynamic feature.

I am looking for a possibility to get the full string of a keypath.

```swift
let keyPath = \Obj.values[1].title
let reflected = reflect(keyPath) // "Obj.values[1].title" 
```
Is this possible with Echo?

**Comment by Azoy** [comment]
Sorry for not commenting on this sooner. Currently this library has basic support for getting the keypath string (only for stored properties) because there's metadata for those components. There's not enough metadata to recover getting the `values` name (there might be a way to show the `1`, but I'm unsure). 

Ideally the standard library adds support for this because the runtime information I'm getting this from is unstable and not ABI, so future versions of Swift could break my basic printing support (which I plan to remove because of the unstableness).

**Comment by lightsprint09** [comment]
Thanks for the details answer :)

Looks like I need to create my first proposal
